export default {
    ADD_SENSOR: 'ADD_SENSOR',
    ADD_MEASURED_VALUE: 'ADD_MEASURED_VALUE',
    EVALUATE_CURRENT_SENSOR: 'EVALUATE_CURRENT_SENSOR',
    RESET_APP: 'RESET_APP',
    SET_REFERENCE: 'SET_REFERENCE'
} as const
